package:
    name: block_diag_ilu
    version: 0.2.0

source:
    fn: block_diag_ilu-0.2.0.tar.gz
    url: https://pypi.python.org/packages/source/b/block_diag_ilu/block_diag_ilu-0.2.0.tar.gz#md5=c51e59508a09e55fa2598ed41db086e7
    md5: c51e59508a09e55fa2598ed41db086e7

build:
    number: 0

requirements:
    build:
      - python
      - numpy
      - cython
      - lapack
    run:
      - python
      - numpy
      - lapack


test:
    requires:
      - python
      - pytest

    imports:
      - block_diag_ilu

about:
    home: https://github.com/chemreac/block_diag_ilu
    license: Simplified BSD license
