package:
    name: pycvodes
    version: 0.4.0

source:
    fn: pycvodes-0.4.0.tar.gz
    url: https://pypi.python.org/packages/source/p/pycvodes/pycvodes-0.4.0.tar.gz#md5=3b7c665070a2fc9c463256f86d530959
    md5: 3b7c665070a2fc9c463256f86d530959

build:
    number: 0

requirements:
    build:
        - python
        - numpy
        - sundials
        - cython
    run:
        - python
        - numpy
        - sundials

test:
    imports:
        - pycvodes
    # requires:
    #     - pytest
    # commands:
    #     - py.test --pyargs pycvodes  # https://github.com/conda/conda/issues/2075, https://github.com/pytest-dev/pytest/issues/1445

about:
    home: https://github.com/bjodah/pycvodes
    license: BSD
