package:
  name: pycvodes
  version: 0.4.2

source:
  fn: pycvodes-0.4.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pycvodes/pycvodes-0.4.2.tar.gz#md5=925f3fd6e9ab65ea258ff0277b8df1ca
  md5: 925f3fd6e9ab65ea258ff0277b8df1ca

build:
  number: 0

requirements:
  build:
   - python
   - numpy
   - sundials
  run:
   - python
   - numpy
   - sundials

test:
  imports:
    - pycvodes

about:
  home: https://github.com/bjodah/pycvodes
  license: BSD
