package:
  name: pycvodes
  version: 0.4.1

source:
  fn: pycvodes-0.4.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pycvodes/pycvodes-0.4.1.tar.gz#md5=17edc03854ecdfd092972b32787d4897
  md5: 17edc03854ecdfd092972b32787d4897

build:
  number: 0

requirements:
  build:
   - python
   - numpy
   - sundials
  run:
   - python
   - numpy
   - sundials

test:
    imports:
        - pycvodes
    # requires:
    #     - pytest
    # commands:
    #     - py.test --pyargs pycvodes  # https://github.com/conda/conda/issues/2075, https://github.com/pytest-dev/pytest/issues/1445

about:
    home: https://github.com/bjodah/pycvodes
    license: BSD
