package:
  name: chemreac
  version: 0.6.1
  # the version being overridden by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

source:
  fn: chemreac-0.6.1.tar.gz
  url: https://github.com/chemreac/chemreac/releases/download/v0.6.1/chemreac-0.6.1.tar.gz
  md5: 0fbd5bf4342076fb7a11657353d03e9c

requirements:
  build:
    - python
    - sundials
    - numpy
    - pycompilation
    - pycodeexport
    - mako
    - block_diag_ilu
    - quantities
    - chempy
    - lapack
  run:
    - python
    - numpy
    - scipy
    - sundials
    - matplotlib
    - sympy
    - quantities
    - chempy
    - block_diag_ilu
    - lapack
    - libgcc

build:
  number: 0

test:
  requires:
    - pytest
    - periodictable
    - argh
  imports:
    - chemreac
  commands:
    - MPLBACKEND=Agg py.test --pyargs chemreac

about:
  home: https://github.com/chemreac/chemreac
  license: BSD License
  summary: Python package for modelling chemical kinetics with diffusion and drift
