package:
  name: chemreac
  version: 0.6.0.git
  # the version being overridden by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

source:
  path: chemreac-0.6.0.git/

build:
  number: 1

requirements:
  build:
    - python
    - sundials
    - cython
    - numpy
    - pycompilation
    - pycodeexport
    - mako
    - block_diag_ilu
    - quantities
    - chempy
    - lapack
  run:
    - libgcc
    - python
    - numpy
    - scipy ==0.16
    - sundials
    - matplotlib
    - sympy
    - quantities
    - chempy
    - block_diag_ilu
    - lapack

# test:
#   requires:
#     - pytest
#     - periodictable
#     - argh
#   imports:
#     - chemreac
#   commands:
#     - MPLBACKEND=Agg py.test --pyargs chemreac

about:
  home: https://github.com/chemreac/chemreac
  license: BSD License
  summary: Python package for modelling chemical kinetics with diffusion and drift
