package:
  name: pycodeexport
  version: "0.1.1"
  # the version is actually being set by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

source:
  fn: pycodeexport-0.1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pycodeexport/pycodeexport-0.1.0.tar.gz#md5=79b43ae236039f734fd38c3fbdd4bd26
  md5: 79b43ae236039f734fd38c3fbdd4bd26

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  requires:
    - pycompilation


about:
  home: https://github.com/bjodah/pycodeexport
  license:  BSD License
  summary: 'Python package for codegeneration.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
