package:
    name: pyodesys
    version: 0.5.2

source:
    fn: pyodesys-0.5.2.tar.gz
    url: https://pypi.python.org/packages/source/p/pyodesys/pyodesys-0.5.2.tar.gz#md5=83f1c6ec0239206c3e2b94355a1f3beb
    md5: 83f1c6ec0239206c3e2b94355a1f3beb

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - sympy
        - scipy

test:
    imports:
        - pyodesys
    requires:
        - pytest
        - scipy
        - pyodeint
        - pygslodeiv2
        - pycvodes

about:
    home: https://github.com/bjodah/pyodesys
    license: BSD
