package:
  name: block_diag_ilu
  version: 0.2.2

source:
  fn: block_diag_ilu-0.2.2.tar.gz
  url: https://pypi.python.org/packages/source/b/block_diag_ilu/block_diag_ilu-0.2.2.tar.gz#md5=e3cafd56eacc7a2a924abd417362a024
  md5: e3cafd56eacc7a2a924abd417362a024

build:
  number: 2

requirements:
  build:
    - python
    - numpy
    - cython
    - lapack
  run:
    - python
    - numpy
    - lapack


test:
  requires:
    - python
    - pytest

  imports:
    - block_diag_ilu

about:
  home: https://github.com/chemreac/block_diag_ilu
  license: Simplified BSD license
