package:
    name: block_diag_ilu
    version: 0.2.1

source:
    fn: block_diag_ilu-0.2.1.tar.gz
    url: https://pypi.python.org/packages/source/b/block_diag_ilu/block_diag_ilu-0.2.1.tar.gz#md5=c8ab75427ced5499be251cda0a701f89
    md5: c8ab75427ced5499be251cda0a701f89

requirements:
  build:
    - python
    - numpy
    - cython
    - lapack
  run:
    - python
    - numpy
    - lapack


test:
  requires:
    - python
    - pytest

  imports:
    - block_diag_ilu

about:
  home: https://github.com/chemreac/block_diag_ilu
  license: Simplified BSD license
