package:
  name: sundials
  version: "2.6.2"

build:
  number: 1

source:
  fn: sundials-2.6.2.tar.gz
  url: http://pkgs.fedoraproject.org/repo/pkgs/sundials/sundials-2.6.2.tar.gz/3deeb0ede9f514184c6bd83ecab77d95/sundials-2.6.2.tar.gz
  md5: 3deeb0ede9f514184c6bd83ecab77d95


requirements:
  build:
    # - gcc
    - cmake
    - lapack

  run:
    # - libgcc
    - lapack

test:
  files:
    - cvRoberts_dns.c

about:
  home: http://computation.llnl.gov/casc/sundials/main.html
  license: BSD
  summary: 'SUit of Nonlinear and DIfferential/ALgebraic equation Solvers'
