package:
  name: pygslodeiv2
  version: 0.5.1

source:
  fn: pygslodeiv2-0.5.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pygslodeiv2/pygslodeiv2-0.5.1.tar.gz#md5=6799d955b3cd4c92f2cf8bbe09506419
  md5: 6799d955b3cd4c92f2cf8bbe09506419

build:
  number: 1

requirements:
  build:
    # - gcc
    - python
    - numpy
    - gsl
  run:
    # - libgcc
    - numpy
    - python
    - gsl

test:
  imports:
    - pygslodeiv2
  requires:
    - pytest

about:
  home: https://github.com/bjodah/pygslodeiv2
  license: GNU GPL v3
