package:
  name: pyodeint
  version: 0.6.0

source:
  fn: pyodeint-0.6.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pyodeint/pyodeint-0.6.0.tar.gz#md5=99048d109f16b9020d95cf1eaf87a0e0
  md5: 99048d109f16b9020d95cf1eaf87a0e0

build:
  number: 1

requirements:
  build:
    # - gcc
    - python
    - numpy
    - boost
  run:
    # - libgcc
    - numpy
    - python

test:
  imports:
    - pyodeint
  requires:
    - pytest

about:
    home: https://github.com/bjodah/pyodeint
    license: Simplified BSD license
