package:
  name: pyneqsys
  version: 0.4.2

source:
  fn: pyneqsys-0.4.2.tar.gz
  url: https://github.com/bjodah/pyneqsys/releases/download/v0.4.2/pyneqsys-0.4.2.tar.gz
  md5: 1d04d5c488456c27fab1a0bb925c1d69

build:
  number: 0

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy
    - sympy
    - scipy
    - pyodesys

test:
  imports:
    - pyneqsys
  requires:
    - nose
  commands:
    - nosetests pyneqsys

about:
  home: https://github.com/bjodah/pyneqsys
  license: BSD
